from .manager import Manager
from .login import Login
from .container import Container
from .inventario import Inventario
from .ventas import Ventas
from .clientes import Clientes
from .pedidos import Pedidos
from .proveedor import Proveedor
from .informacion import Informacion